<!DOCTYPE html>
<html>
<head>
    <?= $this->tag->stylesheetLink("css/bootstrap.min.css") ?>
    <?= $this->tag->stylesheetLink("css/backend/style.css") ?>
    <?= $this->tag->javascriptInclude("js/jquery-2.1.4.min.js") ?>
    <?= $this->tag->javascriptInclude("js/bootstrap.min.js") ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->tag->getTitle(); ?>
</head>
<body>
<div class="container">
<?php echo $this->getContent(); ?>
</div>
</body>
</html>
