<!DOCTYPE html>
<html>
<head>
    <?= $this->tag->stylesheetLink("css/bootstrap.min.css") ?>
    <?= $this->tag->stylesheetLink("css/backend/style.css") ?>
    <?= $this->tag->javascriptInclude("js/jquery-2.1.4.min.js") ?>
    <?= $this->tag->javascriptInclude("js/bootstrap.min.js") ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->tag->getTitle(); ?>
</head>
<body>
<?php $this->partial("layouts/navigate"); ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="list-group text-center">
                    <a href="#" class="list-group-item disabled">系统设置</a>
                    <a href="#" class="list-group-item">网站基本参数</a>
                    <a href="#" class="list-group-item">账户安全管理</a>
                    <a href="#" class="list-group-item disabled">网站内容管理</a>
                    <a href="#" class="list-group-item">栏目管理</a>
                    <a href="#" class="list-group-item">文章列表</a>
                    <a href="#" class="list-group-item">添加文章</a>
                    <a href="#" class="list-group-item disabled">模块管理</a>
                    <a href="#" class="list-group-item">留言管理</a>
                    <a href="#" class="list-group-item">友情链接</a>
                </div>
            </div>
            <div class="col-md-9">
            <?php echo $this->getContent(); ?>
            </div>
        </div>
        <div class="row">
            <?php $this->partial("layouts/footer"); ?>
        </div>
    </div>
</body>
</html>
