
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("admin/carousel/new", "Create carousel")) ?>
</div>

<?php echo $this->tag->form(array("admin/carousel/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search carousel</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="url">Url</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("url", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="image">Image</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("image", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="active">Active</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("active",  array("0" => "开启", "1" => "关闭"))) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
