
<?php echo $this->tag->form("admin/carousel/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("admin/carousel", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Carousel</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="title">标题</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 60)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="url">链接</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("url", "size" => 60)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="image">图片地址</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("image", "size" => 60)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">描述</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 60)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="active">状态</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("active",  array("0" => "开启", "1" => "不开启"))) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
