
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("admin/app/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("admin/app", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit App Set</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="name">站点名</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="http">网址</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("http", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="keywords">关键词</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("keywords", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">站点描述</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="icp">备案ICP</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("icp", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">联系邮箱</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="tel">电话</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("tel", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fax">传真</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fax", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="address">地址</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("address", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
