
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("comment/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("comment", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit comment</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="aid">Aid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("aid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="author">Author</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("author", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="datetime">Datetime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("datetime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
