
<?php echo $this->getContent() ?>

<?php echo $this->tag->form(array("admin/comment/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search comment</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="aid">Aid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("aid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="author">Author</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("author", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="datetime">Datetime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("datetime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
