<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("admin/comment/index", "Go Back")); ?>
        </td>
        <td align="right"></td>
    </tr>
</table>

<table class="table table-hover" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>文章标题</th>
            <th>评论者</th>
            <th>评论内容</th>
            <th>时间</th>
            <th>是否审核</th>
            <th>审核</th>
            <th>删除</th>
         </tr>
    </thead>
    <tbody>
    <?php $status = array( 0 => '<span style="color:green;">已审核</span>', 1 =>'<span style="color:red;">未审核</span>');?>
    <?php foreach ($page->items as $comment) { ?>
        <tr>
            <td><?php echo $comment->id ?></td>
            <td><?php echo \News\Admin\Models\Article::findFirst("id = $comment->aid")->title ?></td>
            <td><?php echo $comment->author ?></td>
            <td><?php echo $comment->content ?></td>
            <td><?php echo $comment->datetime ?></td>
            <td><?php echo $status[$comment->status] ?></td>
            <td><?php echo $this->tag->linkTo(array("admin/comment/approve/" . $comment->id, "Approve")); ?></td>
            <td><?php echo $this->tag->linkTo(array("admin/comment/delete/" . $comment->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<nav>
    <ul class="pagination">
        <li title="首页"><?php echo $this->tag->linkTo("admin/comment/search", "&laquo;") ?></li>
        <li title="前一页"><?php echo $this->tag->linkTo("admin/comment/search?page=" . $page->before, "&lsaquo;") ?></li>
        <li title="后一页"><?php echo $this->tag->linkTo("admin/comment/search?page=" . $page->next, "&rsaquo;") ?></li>
        <li title="末页"><?php echo $this->tag->linkTo("admin/comment/search?page=" . $page->last, "&raquo;") ?></li>
        <li><a href="#"><?php echo $page->current, " / ", $page->total_pages ?></a></li>
        
    </ul>
</nav>