
<?php echo $this->tag->form("admin/admin/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("admin/admin", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Admin</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="user_name">用户名</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">真实姓名</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">密码</label>
        </td>
        <td align="left">
            <?php echo $this->tag->passwordField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">邮箱</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">权限</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("group",  array("0" => "超级管理员", "1" => "普通管理员"))) ?>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
