<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Library</a></li>
  <li class="active">Data</li>
</ol>

<table class="table table-hover" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>真实姓名</th>
            <th>登陆密码</th>
            <th>邮箱</th>
            <th>编辑</th>
            <th>删除</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $admin) { ?>
        <tr>
            <td><?php echo $admin->id ?></td>
            <td><?php echo $admin->user_name ?></td>
            <td><?php echo $admin->name ?></td>
            <td>********</td>
            <td><?php echo $admin->email ?></td>
            <td><?php echo $this->tag->linkTo(array("admin/admin/edit/" . $admin->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("admin/admin/delete/" . $admin->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("admin/admin/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("admin/admin/new", "Create ")); ?>
        </td>
    </tr>
</table>
<nav>
    <ul class="pagination">
        <li title="首页"><?php echo $this->tag->linkTo("admin/admin/search", "&laquo;") ?></li>
        <li title="前一页"><?php echo $this->tag->linkTo("admin/admin/search?page=" . $page->before, "&lsaquo;") ?></li>
        <li title="后一页"><?php echo $this->tag->linkTo("admin/admin/search?page=" . $page->next, "&rsaquo;") ?></li>
        <li title="末页"><?php echo $this->tag->linkTo("admin/admin/search?page=" . $page->last, "&raquo;") ?></li>
        <li><a href="#"><?php echo $page->current, " / ", $page->total_pages ?></a></li>
    </ul>
</nav>
