<?php use Phalcon\Tag; ?>

<ol class="breadcrumb">
  <li><?php echo $this->tag->linkTo(array("admin/index", '<i class="glyphicon glyphicon-home"></i> 后台首页 ')); ?></li>
  <li class="active">管理员账号列表</li>
</ol>

<?php echo $this->getContent(); ?>

<table class="table table-hover" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>真实姓名</th>
            <th>权限</th>
            <th>邮箱</th>
            <th>编辑</th>
            <th>删除</th>
         </tr>
    </thead>
    <tbody>
    <?php $group = array( 0 => '超级管理员', 1 => '普通管理员');?>
    <?php foreach ($page->items as $admin) { ?>
        <tr>
            <td><?php echo $admin->id ?></td>
            <td><?php echo $admin->user_name ?></td>
            <td><?php echo $admin->name ?></td>
            <td><?php echo $group[$admin->group] ?></td>
            <td><?php echo $admin->email ?></td>
            <td><?php echo $this->tag->linkTo(array("admin/admin/edit/" . $admin->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("admin/admin/delete/" . $admin->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<nav>
    <ul class="pagination">
        <li title="首页"><?php echo $this->tag->linkTo("admin/admin/search", "&laquo;") ?></li>
        <li title="前一页"><?php echo $this->tag->linkTo("admin/admin/search?page=" . $page->before, "&lsaquo;") ?></li>
        <li title="后一页"><?php echo $this->tag->linkTo("admin/admin/search?page=" . $page->next, "&rsaquo;") ?></li>
        <li title="末页"><?php echo $this->tag->linkTo("admin/admin/search?page=" . $page->last, "&raquo;") ?></li>
        <li><a href="#"><?php echo $page->current, " / ", $page->total_pages ?></a></li>
        <li><?php echo $this->tag->linkTo(array("admin/admin/index", "返回", "class" => "btn btn-info btn-sm")); ?></li>
        <li><?php echo $this->tag->linkTo(array("admin/admin/new", "创建 ", "class" => "btn btn-success btn-sm")); ?></li>
    </ul>
</nav>
