<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
    <?php for ($i=0; $i < count($carousel); $i++) { ?>
        <?php if ($i == 1): ?>
            <li data-target="#carousel-example-generic" data-slide-to="<?=$i?>" class="active"></li>
        <?php else: ?>
            <li data-target="#carousel-example-generic" data-slide-to="<?=$i?>" class=""></li>
        <?php endif ?>
    <?php } ?>
    </ol>

    <div class="carousel-inner" role="listbox" id="carousel-inner">
    <?php $i = 0;?>
    <?php foreach ($carousel as $ads): ?>
        <?php if ($i == 1): ?>
        <div class="item active">
        <?php else: ?>
        <div class="item">
        <?php endif ?>
            <a href="<?=$ads->url?>" target="_blank"><img alt="<?=$ads->title?>" src="<?=$ads->image?>" data-holder-rendered="true"></a>
        </div>
        <?php $i++;?>
    <?php endforeach ?>
    </div>

    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">上一张</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">下一张</span>
    </a>
</div>

<div class="page-header">
    <h1>热门推荐!</h1>
</div>

<div class="row">
<?php foreach ($page->items as $val): ?>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img data-src="" alt="" src="<?= GetImage::getFirstImage($val->content) ?>" data-holder-rendered="true">
            <div class="caption">
                <h3><?= $this->tag->linkTo("article/get/".$val->id, $val->title) ?></h3>
                <p><span>作者: <?= $val->author ?></span></p>
                <p><span>日期: <?= $val->datetime ?></span></p>
                <p><span>来源: <?= $val->origin ?></span></p>
            </div>
        </div>
    </div>       
<?php endforeach ?>
</div>

<nav class="text-center">
    <ul class="pagination">
        <li title="首页"><?php echo $this->tag->linkTo("article/search", "首页") ?></li>
        <li title="前一页"><?php echo $this->tag->linkTo("article/search?page=" . $page->before, "前一页") ?></li>
        <li title="后一页"><?php echo $this->tag->linkTo("article/search?page=" . $page->next, "后一页") ?></li>
        <li title="末页"><?php echo $this->tag->linkTo("article/search?page=" . $page->last, "末页") ?></li>
        <li><a href="#"><?php echo $page->current, " / ", $page->total_pages ?></a></li>
    </ul>
</nav>