
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("admin/classis/new", "Create classis")) ?>
</div>

<?php echo $this->tag->form(array("admin/classis/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search classis</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="keywords">Keywords</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("keywords", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="sort">Sort</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("sort", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
