
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("admin/classis/new", "Create classis")) ?>
</div>

<?php echo $this->tag->form(array("admin/classis/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search Classis</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="id">ID</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">栏目名称</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="keywords">关键词</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("keywords", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">描述</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="sort">排序</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("sort")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
