
<?php echo $this->tag->form("admin/classis/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("admin/classis", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Classis</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="name">栏目名称</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="keywords">关键词</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("keywords", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">描述</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="sort">排序</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("sort")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
