<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-8" aria-expanded="false">
                <span class="sr-only">折叠</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo" href="<?= $this->url->get("") ?>">
                <?= $this->tag->image(array("images/logo.png","alt" => $app->name, "title" => $app->name)) ?>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8">
            <ul class="nav navbar-nav">
            <?php if ($this->dispatcher->getControllerName() == 'index'): ?>
                <li class="active">
            <?php else: ?>
                <li>
            <?php endif ?>
                    <?= $this->tag->linkTo(array("index", '首页')) ?>
                </li>
            <?php foreach ($navigate as $menu): ?>
            <?php if ($classis_id == $menu->id): ?>
                <li class="active">
            <?php else: ?>
                <li>    
            <?php endif ?>
                    <?= $this->tag->linkTo(array("classis/search/".$menu->id, $this->dispatcher->getParam("id").$menu->name)) ?></li>
            <?php endforeach ?>
            </ul>
        </div>

    </div>
</nav>
