<div>
    <h3><?= $classis_name ?></h3>
</div>

<div class="row">
<?php foreach ($page->items as $val): ?>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <?= $this->tag->image(array(GetImage::getFirstImage($val->content), "data-holder-rendered" => "true"))?>
            <div class="caption">
                <h3><?= $this->tag->linkTo("article/get/".$val->id, $val->title) ?></h3>
                <p><span>作者: <?= $val->author ?></span></p>
                <p><span>日期: <?= $val->datetime ?></span></p>
                <p><span>来源: <?= $val->origin ?></span></p>
            </div>
        </div>
    </div>       
<?php endforeach ?>
</div>

<nav class="text-center">
    <ul class="pagination">
        <li title="首页"><?php echo $this->tag->linkTo("classis/search/".$classis_id, "首页") ?></li>
        <li title="前一页"><?php echo $this->tag->linkTo("classis/search/".$classis_id."?page=" . $page->before, "前一页") ?></li>
        <li title="后一页"><?php echo $this->tag->linkTo("classis/search/".$classis_id."?page=" . $page->next, "后一页") ?></li>
        <li title="末页"><?php echo $this->tag->linkTo("classis/search/".$classis_id."?page=" . $page->last, "末页") ?></li>
        <li><a href="#"><?php echo $page->current, " / ", $page->total_pages ?></a></li>
    </ul>
</nav>