    <nav>
        <div class="col-md-2">
            <div><img src="logo"></div>
        </div>
        <div class="col-md-10">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user"></i> <?=$this->session->get('auth')['true_name']?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><?php echo $this->tag->linkTo(array("admin/admin/edit/".$this->session->get('auth')['id'], "资料修改")) ?></li>
                        <li role="separator" class="divider"></li>
                        <li><?php echo $this->tag->linkTo(array("admin/login/exit", "退出系统")) ?></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="col-md-3">
        <?php $this->partial("layouts/sidebar"); ?>
        </div>
        <div class="col-md-9">
        <?php echo $this->getContent(); ?>
        </div>
    </div>
    <div class="row">
    <?php $this->partial("layouts/footer"); ?>
    </div>
