    <header>
        <nav>
            <div class="col-md-2">
                <div><img src="logo"></div>
            </div>
            <div class="col-md-10">
                <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                </ul>
                </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
            <?php $this->partial("layouts/sidebar"); ?>
            </div>
            <div class="col-md-9">
            <?php echo $this->getContent(); ?>
            </div>
        </div>
        <div class="row">
        <?php $this->partial("layouts/footer"); ?>
        </div>
    </div>

