    <nav>
        <div class="col-md-2">
            <div class="bk_logo">
                <a href="<?= $this->url->get("admin/") ?>">
                    <?= $this->tag->image(array("images/bk_logo.png","alt" => $app->name, "title" => $app->name)) ?>
                </a>
            </div>
        </div>
        <div class="col-md-10">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?= $this->url->get("") ?>" target="_blank"><i class="glyphicon glyphicon-home"></i> 网站主页</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user"></i> <?=$this->session->get('auth')['true_name']?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><?php echo $this->tag->linkTo(array("admin/admin/edit/".$this->session->get('auth')['id'], '<i class="glyphicon glyphicon-briefcase"></i> 资料修改')) ?></li>
                        <li role="separator" class="divider"></li>
                        <li><?php echo $this->tag->linkTo(array("admin/login/exit", '<i class="glyphicon glyphicon-off"></i> 退出系统')) ?></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="col-md-3">
        <?php $this->partial("layouts/sidebar"); ?>
        </div>
        <div class="col-md-9">
        <?php echo $this->getContent(); ?>
        </div>
    </div>
    <div class="row">
    <?php $this->partial("layouts/footer"); ?>
    </div>
