    <div class="list-group text-center" id="sidebar">
        <a href="#" class="list-group-item disabled"><i class="glyphicon glyphicon-cog"></i> 系统设置</a>
        <?php echo $this->tag->linkTo(array("admin/app", "基本设置", "class" => "list-group-item")) ?>
        <?php echo $this->tag->linkTo(array("admin/admin", "账户管理", "class" => "list-group-item")) ?>
        <?php echo $this->tag->linkTo(array("admin/carousel/search", "广告轮播", "class" => "list-group-item")) ?>
        <a href="#" class="list-group-item disabled"><i class="glyphicon glyphicon-list-alt"></i> 内容管理</a>
        <?php echo $this->tag->linkTo(array("admin/classis/search", "栏目管理", "class" => "list-group-item")) ?>
        <?php echo $this->tag->linkTo(array("admin/article/search", "文章列表", "class" => "list-group-item")) ?>
        <?php echo $this->tag->linkTo(array("admin/article/new", "文章发布", "class" => "list-group-item")) ?>
        <a href="#" class="list-group-item disabled"><i class="glyphicon glyphicon-equalizer"></i> 模块管理</a>
        <?php echo $this->tag->linkTo(array("admin/comment/search", "评论管理", "class" => "list-group-item")) ?>
        <?php echo $this->tag->linkTo(array("admin/friendly_link/search", "友情链接", "class" => "list-group-item")) ?>
    </div>