    <div class="list-group text-center">
        <a href="#" class="list-group-item disabled">系统设置</a>
        <a href="#" class="list-group-item">网站基本参数</a>
        <a href="#" class="list-group-item">账户安全管理</a>
        <a href="#" class="list-group-item disabled">网站内容管理</a>
        <a href="#" class="list-group-item">栏目管理</a>
        <a href="#" class="list-group-item">文章列表</a>
        <a href="#" class="list-group-item">添加文章</a>
        <a href="#" class="list-group-item disabled">模块管理</a>
        <a href="#" class="list-group-item">留言管理</a>
        <a href="#" class="list-group-item">友情链接</a>
    </div>