
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("admin/article/new", "Create article")) ?>
</div>

<?php echo $this->tag->form(array("admin/article/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search article</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cid">Cid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("cid", \News\Admin\Models\Classis::find(),"using" => array("id", "name"))) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="author">Author</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("author", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="origin">Origin</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("origin", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="keywords">Keywords</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("keywords", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("content", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="datetime">Datetime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("datetime", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
