
<?php echo $this->tag->form("admin/article/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("admin/article", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Article</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="cid">栏目</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("cid", \News\Admin\Models\Classis::find(),"using" => array("id", "name"))) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">标题</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="author">作者</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("author", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="origin">来源</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("origin", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="keywords">关键词</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("keywords", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">内容</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("content", "cols" => 80, "rows" => 15)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
