
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("admin/friendly_link/new", "Create friendly_link")) ?>
</div>

<?php echo $this->tag->form(array("admin/friendly_link/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search Friendly Link</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="id">ID</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">名称</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="url">链接</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("url", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">描述</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">状态</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
