
<?php echo $this->tag->form("admin/friendly_link/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("admin/friendly_link", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Friendly Link</h1>
</div>

<table class="table">
    <tr>
        <td align="right">
            <label for="name">名称</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="url">链接</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("url", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">描述</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">状态</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("status",  array("0" => "已审核", "1" => "未审核"))) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
